### ISSUE TITLE
Integrate Command Dictionary with LLM for Service-Based Recon Suggestions

### ISSUE THREAD

**Issue by jackhax** [jackhax/Hawx-Recon-Agent#35]
Currently, the LLM generates recon commands from scratch based on detected services. To improve accuracy, consistency, and control, we should maintain a structured **command dictionary** (e.g., `commands.yaml`) containing recon commands categorized by service or task.

### Proposed Solution

- Create a `commands.yaml` that maps services and recon tasks to common command templates, for example:

```yaml
web:
  dir_enum:
    - gobuster dir -u {{URL}} -w /usr/share/seclists/Discovery/Web-Content/common.txt
    - ffuf -u {{URL}}/FUZZ -w /usr/share/seclists/Discovery/Web-Content/directory-list-2.3-medium.txt
  vuln_scan:
    - nikto -h {{URL}}

ftp:
  - nmap -p 21 --script ftp-anon {{IP}}
  - ftp {{IP}}

smb:
  - smbclient -L //{{IP}} -N
  - enum4linux-ng -A {{IP}}
```

- When a service is detected (e.g., `http`, `ftp`, `smb`), look up its associated commands from this dictionary.
- Send only those commands to the LLM to **rank, prioritize, or refine**.
- If no entry is found for a service, fallback to full LLM-based command generation.

### Token Efficiency Considerations

To avoid exceeding LLM token limits:
- Limit the number of commands sent per category
- Chunk and chain commands across multiple prompts
- Use short tags like `ffuf_basic`, `nikto_default`, etc., in the prompt and map them back to full commands internally

### Benefits

- Prevents LLM command hallucination
- Encourages consistent, reusable recon strategies
- Makes prompts shorter and more relevant
- Provides an extensible way to add or override recon logic for known services

---

Let me know if you'd like help bootstrapping `commands.yaml` or implementing a `CommandRecommender` module.
